### ISSUE TITLE
composer installation add .git folder 

### ISSUE THREAD

**Issue by itaymesh** [Magento2Translations/language_he_il#2]
Hi,
I have noticed that when installing the language package via composer it also download the .git folder.
It causes a conflict with the root .git repo.
Is it possible to exclude the .git repo from the installation files?

**Comment by MrGekko** [comment]
Hi, thanks for using this package! The.git folder is created because when composer uses the dev-master(latest commit) it clones the git repo (including the .git folder).
You could try resolving this using the --prefer-dist flag for the `update `& `install `commands for composer.
`composer update --prefer-dist`
But I doubt that will download the latest commit.
A other solution would be running `find . -type d | grep .git | xargs rm -rf` to cleanup the .git folders in vendor.

Source of solutions:
http://stackoverflow.com/questions/25981292/how-to-make-composer-not-create-a-git-directory-for-a-package

**Comment by MrGekko** [comment]
Or you clould just add /vendor to your gitignore file and the whole vendor folder would not be conflicting.
Maybe adding /vendor/**/.git would work great for your usecase?
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by itaymesh** [comment]
@MrGekko I will stick with manually removing the .git folder. 
Thanks

**Comment by sunz5010** [comment]
Hi, you can install php zip extension.
I solve this problem when I install php zip extension.
I think composer can not unzip dist repo files, so that it clone file from git repo, so that it will contain .git folder.
